kind: EventList
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: {{ .Values.global.compositionKind | lower }}-{{ .Values.global.compositionName }}-composition-events-panel-eventlist
  namespace: {{ .Values.global.compositionNamespace }}
spec:
  widgetData:
    events: []
    sseEndpoint: "/notifications/"
    sseTopic: "{{ .Values.global.compositionId }}"
  widgetDataTemplate:
    - forPath: events
      expression: >
        ${
          .list
          | map(
              .firstTimestamp = ( if (.firstTimestamp // "") == "" 
                                  then (.eventTime // .lastTimestamp // null) 
                                  else .firstTimestamp 
                                end ) |
              .lastTimestamp  = ( if (.lastTimestamp // "") == "" 
                                  then (.firstTimestamp // .eventTime // null) 
                                  else .lastTimestamp 
                                end ) |
              .eventTime      = ( if (.eventTime // "") == "" 
                                  then (.firstTimestamp // .lastTimestamp // null) 
                                  else .eventTime 
                                end ) |
              .involvedObject.namespace = (.involvedObject.namespace // "") |
              del(
                .metadata.resourceVersion,
                .metadata.annotations,
                .metadata.labels,
                .metadata.managedFields,
                .metadata.generatedName,
                .involvedObject.resourceVersion,
                .series
              )
            )
        }
  apiRef:
    name: {{ .Values.global.compositionKind | lower }}-{{ .Values.global.compositionName }}-composition-events
    namespace: {{ .Values.global.compositionNamespace }}