apiVersion: templates.krateo.io/v1
kind: RESTAction
metadata:
  name: {{ .Values.global.compositionKind | lower }}-{{ .Values.global.compositionName }}-composition-schema
  namespace: {{ .Values.global.compositionNamespace }}
spec:
  api:
  - name: getCompositionSpec
    path: "/apis/{{ .Values.global.compositionGroup }}/{{ .Values.global.compositionInstalledVersion }}/namespaces/{{ .Values.global.compositionNamespace }}/{{ .Values.global.compositionResource }}/{{ .Values.global.compositionName }}"
    verb: GET
    filter: ".getCompositionSpec | .spec"
  - name: getCompositionMetadata
    path: "/apis/{{ .Values.global.compositionGroup }}/{{ .Values.global.compositionInstalledVersion }}/namespaces/{{ .Values.global.compositionNamespace }}/{{ .Values.global.compositionResource }}/{{ .Values.global.compositionName }}"
    verb: GET
    filter: ".getCompositionMetadata | .metadata | {name: .name, namespace: .namespace}"
  - name: getOrderedSchema
    path: ${ "/apis/apiextensions.k8s.io/v1/customresourcedefinitions/{{ .Values.global.compositionResource }}.composition.krateo.io" }
    verb: GET
    filter: >
      .getOrderedSchema.spec.versions[] | select(.name == "{{ .Values.global.compositionInstalledVersion }}") | .schema.openAPIV3Schema.properties.spec
  - name: getCompositionDefinitionNamespace
    endpointRef:
      name: resources-presenter-endpoint
      namespace: {{ .Values.global.krateoNamespace }}
    path: "/resources?group=core.krateo.io&version=v1alpha1&resource=compositiondefinitions&namespace=*&raw=true&status_raw=true&limit=5000"
    verb: GET
    exportJwt: true
    continueOnError: true
    filter: >
      [ .getCompositionDefinitionNamespace.items[]?
        | select((.status_raw.resource // .raw.status.resource) == "{{ .Values.global.compositionResource }}")
        | .namespace ]
  - name: getNotOrderedSchema
    dependsOn:
      name: getCompositionDefinitionNamespace
    path: ${ "/api/v1/namespaces/"+ (.getCompositionDefinitionNamespace[0]) + "/configmaps/{{ .Values.global.compositionResource }}-{{ .Values.global.compositionInstalledVersion }}-jsonschema-configmap" }
    verb: GET
    filter: >
      .getNotOrderedSchema.data["values.schema.json"]